from flask import Flask, request, session, redirect, url_for, render_template_string, abort
import secrets

app = Flask(__name__)

# Secret key used by Flask to manage sessions.
# This is only for the controlled university demonstration.
app.secret_key = "csrf-demo-secret-key"


# ============================================================
# DEMO USER
# ============================================================

users = {
    "student": {
        "password": "password123",
        "email": "student@example.com"
    }
}


# ============================================================
# LOGIN PAGE
# ============================================================

LOGIN_PAGE = """
<!DOCTYPE html>
<html>
<head>
    <title>CSRF Demo - Login</title>
</head>

<body>

    <h1>CSRF Vulnerability Demonstration</h1>

    <h2>Login</h2>

    <form method="POST" action="/login">

        <label>Username:</label>
        <input type="text" name="username" required>

        <br><br>

        <label>Password:</label>
        <input type="password" name="password" required>

        <br><br>

        <button type="submit">Login</button>

    </form>

    <br>

    <p>
        <strong>Demo credentials:</strong>
    </p>

    <p>
        Username: student<br>
        Password: password123
    </p>

</body>
</html>
"""


# ============================================================
# PROFILE PAGE
# ============================================================

PROFILE_PAGE = """
<!DOCTYPE html>
<html>
<head>
    <title>CSRF Demo - Profile</title>
</head>

<body>

    <h1>User Profile</h1>

    <p>
        Logged in as:
        <strong>{{ username }}</strong>
    </p>

    <p>
        Current email:
        <strong>{{ email }}</strong>
    </p>

    <hr>

    <h2>Change Email</h2>

    <!--
    ==========================================================
    CSRF MITIGATION - SYNCHRONIZER TOKEN PATTERN
    ==========================================================

    This state-changing form contains a CSRF token generated
    for the authenticated user's session.

    The server validates the submitted token before allowing
    the email address to be changed.

    A forged request that does not contain the correct token
    is rejected with HTTP 403 Forbidden.
    ==========================================================
    -->

    <form method="POST" action="/change-email">

        <!--
    CSRF token generated by the server and associated
    with the authenticated user's session.
    -->
    <input
        type="hidden"
        name="csrf_token"
        value="{{ csrf_token }}"
    

        <label>New Email:</label>

        <input
            type="email"
            name="email"
            required
        >

        <button type="submit">
            Change Email
        </button>

    </form>

    <br>

    <a href="/logout">Logout</a>

</body>
</html>
"""


# ============================================================
# HOME PAGE
# ============================================================

@app.route("/")
def home():

    if "username" in session:
        return redirect(url_for("profile"))

    return redirect(url_for("login"))


# ============================================================
# LOGIN
# ============================================================

@app.route("/login", methods=["GET", "POST"])
def login():

    if request.method == "POST":

        username = request.form.get("username")
        password = request.form.get("password")

        # Check the demo user's credentials.
        if (
            username in users
            and users[username]["password"] == password
        ):

            # Store the authenticated user in the session.
            session["username"] = username

            # Generate a cryptographically secure CSRF token.
            session["csrf_token"] = secrets.token_urlsafe(32)

            return redirect(url_for("profile"))

        return """
        <h2>Invalid username or password.</h2>

        <a href="/login">
            Try Again
        </a>
        """

    return render_template_string(LOGIN_PAGE)


# ============================================================
# PROFILE
# ============================================================

@app.route("/profile")
def profile():

    # User must be logged in.
    if "username" not in session:
        return redirect(url_for("login"))

    username = session["username"]

    return render_template_string(
        PROFILE_PAGE,
        username=username,
        email=users[username]["email"],
        csrf_token=session["csrf_token"]
    )


# ============================================================
# SECURITY-ENHANCED CHANGE EMAIL ENDPOINT
# ============================================================

@app.route("/change-email", methods=["POST"])
def change_email():

    # --------------------------------------------------------
    # Authentication check
    # --------------------------------------------------------

    if "username" not in session:
        return "You must be logged in.", 401

    username = session["username"]

    # ========================================================
    # CSRF PROTECTION - SYNCHRONIZER TOKEN PATTERN
    # ========================================================

    submitted_token = request.form.get("csrf_token")
    session_token = session.get("csrf_token")

    if (
        not submitted_token
        or not session_token
        or not secrets.compare_digest(submitted_token, session_token)
    ):
        print("\n========================================")
        print("CSRF ATTACK BLOCKED")
        print("========================================")
        print(f"User: {username}")
        print("Reason: Missing or invalid CSRF token")
        print("Request rejected with HTTP 403.")
        print("========================================\n")

        abort(403)

    new_email = request.form.get("email")


    if not new_email:
        return "Email address is required.", 400


    # ========================================================
    # CSRF MITIGATION
    # ========================================================
    #
    # The submitted CSRF token has been successfully matched
    # against the token stored in the authenticated session.
    #
    # Only after successful validation does the application
    # perform the state-changing operation.
    #
    # Requests with missing or invalid tokens are rejected
    # before the user's email can be modified.
    # ========================================================

    old_email = users[username]["email"]

    # Perform the state-changing operation.
    users[username]["email"] = new_email


    # --------------------------------------------------------
    # Console logging for demonstration/evidence
    # --------------------------------------------------------

    print("\n========================================")
    print("EMAIL CHANGE REQUEST")
    print("========================================")
    print(f"User: {username}")
    print(f"Previous email: {old_email}")
    print(f"New email: {new_email}")
    print("CSRF token: VALID")
    print("Request accepted.")
    print("========================================\n")


    return f"""
    <!DOCTYPE html>

    <html>

    <head>
        <title>Email Changed</title>
    </head>

    <body>

        <h1>Email Changed Successfully</h1>

        <p>
            User:
            <strong>{username}</strong>
        </p>

        <p>
            Previous email:
            <strong>{old_email}</strong>
        </p>

        <p>
            New email:
            <strong>{new_email}</strong>
        </p>

        <br>

        <a href="/profile">
            Return to Profile
        </a>

    </body>

    </html>
    """


# ============================================================
# LOGOUT
# ============================================================

@app.route("/logout")
def logout():

    session.clear()

    return redirect(url_for("login"))


# ============================================================
# START APPLICATION
# ============================================================

if __name__ == "__main__":

    app.run(
        host="127.0.0.1",
        port=5000,
        debug=True
    )
